### ISSUE TITLE
Don`t work

### ISSUE THREAD

**Issue by IgorDePaula** [holasoycael/mercadopago-frontend-nextjs#1]
Nothing console error or warning, Nothing terminal error or warning.

**Comment by holasoycael** [comment]
> Nothing console error or warning, Nothing terminal error or warning.

Hi there!! I'm install repository and run command to open serve in localhost and works good.
What appears to you?

**Comment by IgorDePaula** [comment]
I does too, but when I out my production key to test, nothing happens, anything, no alerts, no console errors or warnings, no terminal errors or warnings, nothing happens. I expect thw payment workflow occur normally. But nothing happens.

**Comment by holasoycael** [comment]
Did you correctly use the keys on the front-end and back-end?

**ACCESS_TOKEN** (_server-side_)
[window.Mercadopago.setPublishableKey](https://github.com/holasoycael/mercadopago-frontend-nextjs/blob/main/src/templates/Home/index.tsx#L47,L50)
**PUBLIC_KEY** (_client-side_)
[mercadopago.configurations.setAccessToken](https://github.com/holasoycael/mercadopago-backend-nodejs/blob/b6b21e0f33227b97e22297366643363bd5619d23/src/services/MercadopagoService.ts#L35,L37)

**Comment by IgorDePaula** [comment]
You app haven't any server side key setting...I setted only pub key on frontend. Maybe is using an old version of js sdk of frontend. By API, the correct is use of v2 of js on frontend.

**Comment by holasoycael** [comment]
> You app haven't any server side key setting...I setted only pub key on frontend. Maybe is using an old version of js sdk of frontend. By API, the correct is use of v2 of js on frontend.

Ahh!! Obviously it's my friend, because both keys are personal. I share my PUBLIC_KEY because no problem. But my ACCESS_TOKEN is confidential, so make sure you use your key.

Follow the steps to configure your settings:

[Dashboard developer from Mercadopago](https://www.mercadopago.com.br/developers/panel)
`References from the first playlist with short videos`
[01. API do Mercado Pago com Node.js — Introdução (11:37-13:22)](https://youtu.be/-ZwJ--ZQUhI?t=697)
[01.1 API do Mercado Pago com Node.js — Credenciais (00:00-00:30)](https://youtu.be/grlvL2VlGkg)
`Second playlist references with more detailed videos`
[01. API do Mercado Pago com Node.js – Introdução (03:42-05:19)](https://youtu.be/4bRRbzU5vGo?t=382)
[01. API do Mercado Pago com Node.js – Introdução (06:22-07:39)](https://youtu.be/4bRRbzU5vGo?t=382)

`About Mercado Pago documentation`
[Credentials section](https://www.mercadopago.com.br/developers/panel/credentials) (See or create your credentials here)
[Credentials](https://www.mercadopago.com.br/developers/pt/docs/checkout-api/additional-content/credentials)

Hope I helped my friend, after completing your settings, please reply to this issue ✨

**Comment by IgorDePaula** [comment]
You could enter anything in the token method, not the real key, and leave your example fully functional, with just the keys swapping. And to say keys are personal is not a smart thing to say, as every dev knows that.
